export type TravelPhoto = {
  src: string;
  alt: string;
  caption?: string;
};

export type TravelPlace = {
  slug: string;
  name: string;
  subtitle: string;
  country?: string;
  date: string;
  cover: string;
  gallery?: TravelPhoto[];
  narrative?: string;
};

export const travelPlaces: TravelPlace[] = [
  {
    slug: 'anaya',
    name: '阿那亚',
    subtitle: 'Aranya, Qinhuangdao',
    country: 'China',
    date: '2024',
    cover: '/travel/anaya/IMG_9073.JPG',
    gallery: [
      { src: '/travel/anaya/FullSizeRender.jpeg', alt: '阿那亚' },
      { src: '/travel/anaya/IMG_9073.JPG', alt: '阿那亚' },
      { src: '/travel/anaya/IMG_9378.JPG', alt: '阿那亚' },
      { src: '/travel/anaya/IMG_9383.JPG', alt: '阿那亚' },
      { src: '/travel/anaya/IMG_9515.JPG', alt: '阿那亚' },
      { src: '/travel/anaya/IMG_9602.JPG', alt: '阿那亚' },
    ],
  },
  {
    slug: 'jiuzhaigou',
    name: '九寨沟',
    subtitle: 'Jiuzhaigou Valley',
    country: 'China',
    date: '2024',
    cover: '/travel/jiuzhaigou/IMG_7798.JPG',
    gallery: [
      { src: '/travel/jiuzhaigou/IMG_7798.JPG', alt: '九寨沟' },
      { src: '/travel/jiuzhaigou/IMG_7817.JPG', alt: '九寨沟' },
      { src: '/travel/jiuzhaigou/IMG_7920.JPG', alt: '九寨沟' },
      { src: '/travel/jiuzhaigou/IMG_7921.JPG', alt: '九寨沟' },
      { src: '/travel/jiuzhaigou/IMG_7926.JPG', alt: '九寨沟' },
    ],
  },
  {
    slug: 'changbaishan',
    name: '长白山',
    subtitle: 'Changbai Mountain',
    country: 'China',
    date: '2024',
    cover: '/travel/changbaishan/IMG_2356.JPG',
    gallery: [
      { src: '/travel/changbaishan/IMG_0129.JPG', alt: '长白山' },
      { src: '/travel/changbaishan/IMG_1990.JPG', alt: '长白山' },
      { src: '/travel/changbaishan/IMG_2041.JPG', alt: '长白山' },
      { src: '/travel/changbaishan/IMG_2108.JPG', alt: '长白山' },
      { src: '/travel/changbaishan/IMG_2216.JPG', alt: '长白山' },
      { src: '/travel/changbaishan/IMG_2356.JPG', alt: '长白山' },
    ],
  },
  {
    slug: 'shenzhen',
    name: '深圳',
    subtitle: 'Shenzhen',
    country: 'China',
    date: '2024',
    cover: '/travel/shenzhen/IMG_6029.JPG',
    gallery: [
      { src: '/travel/shenzhen/IMG_2022.jpeg', alt: '深圳' },
      { src: '/travel/shenzhen/IMG_6029.JPG', alt: '深圳' },
      { src: '/travel/shenzhen/IMG_6137.jpeg', alt: '深圳' },
      { src: '/travel/shenzhen/livePhoto_1768105772.jpeg', alt: '深圳' },
    ],
  },
  {
    slug: 'spain',
    name: '西班牙',
    subtitle: 'Spain',
    country: 'Spain',
    date: '2024',
    cover: '/travel/spain/IMG_1604.JPG',
    gallery: [
      { src: '/travel/spain/IMG_0114.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_1330.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_1598.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_1599.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_1604.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_1754.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_1884.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_2004.JPG', alt: '西班牙' },
      { src: '/travel/spain/IMG_4943.JPG', alt: '西班牙' },
    ],
  },
  {
    slug: 'korea',
    name: '韩国',
    subtitle: 'South Korea',
    country: 'South Korea',
    date: '2024',
    cover: '/travel/korea/IMG_3445.JPG',
    gallery: [
      { src: '/travel/korea/IMG_3445.JPG', alt: '韩国' },
      { src: '/travel/korea/IMG_3502.JPG', alt: '韩国' },
      { src: '/travel/korea/IMG_3581.JPG', alt: '韩国' },
      { src: '/travel/korea/IMG_3583.JPG', alt: '韩国' },
      { src: '/travel/korea/IMG_3589.PNG', alt: '韩国' },
      { src: '/travel/korea/IMG_3595.JPG', alt: '韩国' },
      { src: '/travel/korea/IMG_8857.jpeg', alt: '韩国' },
      { src: '/travel/korea/IMG_9002.JPG', alt: '韩国' },
      { src: '/travel/korea/IMG_9003.JPG', alt: '韩国' },
      { src: '/travel/korea/IMG_9693.JPG', alt: '韩国' },
      { src: '/travel/korea/3D51E9AD-5454-40B5-8A40-B6A919DAF20E-59082-000009F7F600E80E.jpg', alt: '韩国' },
    ],
  },
  {
    slug: 'sanya',
    name: '三亚',
    subtitle: 'Sanya, Hainan',
    country: 'China',
    date: '2025',
    cover: '/travel/sanya/IMG_2471.JPG',
    gallery: [
      { src: '/travel/sanya/IMG_1861.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_1922.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_2063.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_2387.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_2394.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_2471.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_2495.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_8853.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_8858.JPG', alt: '三亚' },
      { src: '/travel/sanya/IMG_9439.JPG', alt: '三亚' },
      { src: '/travel/sanya/Live_20251105170735595.jpeg', alt: '三亚' },
      { src: '/travel/sanya/livePhoto_1762439251.jpeg', alt: '三亚' },
      { src: '/travel/sanya/livePhoto_1762439323.jpeg', alt: '三亚' },
    ],
  },
  {
    slug: 'switzerland',
    name: '瑞士',
    subtitle: 'Switzerland',
    country: 'Switzerland',
    date: '2024',
    cover: '/travel/switzerland/IMG_3696.JPG',
    gallery: [
      { src: '/travel/switzerland/IMG_3462.JPG', alt: '瑞士' },
      { src: '/travel/switzerland/IMG_3492.JPG', alt: '瑞士' },
      { src: '/travel/switzerland/IMG_3668.JPG', alt: '瑞士' },
      { src: '/travel/switzerland/IMG_3696.JPG', alt: '瑞士' },
      { src: '/travel/switzerland/IMG_3711.JPG', alt: '瑞士' },
      { src: '/travel/switzerland/IMG_3729.JPG', alt: '瑞士' },
      { src: '/travel/switzerland/IMG_3732.JPG', alt: '瑞士' },
      { src: '/travel/switzerland/IMG_3756.JPG', alt: '瑞士' },
    ],
  },
  {
    slug: 'chongqing',
    name: '重庆',
    subtitle: 'Chongqing',
    country: 'China',
    date: '2024',
    cover: '/travel/chongqing/IMG_4080.JPG',
    gallery: [
      { src: '/travel/chongqing/IMG_0608.JPG', alt: '重庆' },
      { src: '/travel/chongqing/IMG_4080.JPG', alt: '重庆' },
    ],
  },
  {
    slug: 'beijing',
    name: '北京',
    subtitle: 'Beijing',
    country: 'China',
    date: '2024',
    cover: '/travel/beijing/IMG_8385.JPG',
    gallery: [
      { src: '/travel/beijing/17c3950b16cdb726bc842db8ccec36d6.jpg', alt: '北京' },
      { src: '/travel/beijing/IMG_1137.jpeg', alt: '北京' },
      { src: '/travel/beijing/IMG_1154.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_1942.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_1952.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_2668.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_2669.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_5902.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_6710.jpeg', alt: '北京' },
      { src: '/travel/beijing/IMG_8368.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_8370.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_8385.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_8430.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_9478.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_9479.JPG', alt: '北京' },
      { src: '/travel/beijing/IMG_9517.jpeg', alt: '北京' },
    ],
  },
  {
    slug: 'chengdu',
    name: '成都',
    subtitle: 'Chengdu',
    country: 'China',
    date: '2024',
    cover: '/travel/chengdu/IMG_8525.JPG',
    gallery: [
      { src: '/travel/chengdu/IMG_8525.JPG', alt: '成都' },
      { src: '/travel/chengdu/IMG_8541.JPG', alt: '成都' },
      { src: '/travel/chengdu/IMG_8608.jpeg', alt: '成都' },
    ],
  },
  {
    slug: 'dalian',
    name: '大连',
    subtitle: 'Dalian',
    country: 'China',
    date: '2024',
    cover: '/travel/dalian/IMG_3800.JPG',
    gallery: [
      { src: '/travel/dalian/IMG_3297.JPG', alt: '大连' },
      { src: '/travel/dalian/IMG_3337.JPG', alt: '大连' },
      { src: '/travel/dalian/IMG_3800.JPG', alt: '大连' },
      { src: '/travel/dalian/IMG_3920.JPG', alt: '大连' },
      { src: '/travel/dalian/IMG_3921.jpeg', alt: '大连' },
      { src: '/travel/dalian/IMG_4652.JPG', alt: '大连' },
      { src: '/travel/dalian/IMG_4850.JPG', alt: '大连' },
      { src: '/travel/dalian/IMG_6421.jpeg', alt: '大连' },
      { src: '/travel/dalian/IMG_6460.jpeg', alt: '大连' },
    ],
  },
  {
    slug: 'france',
    name: '法国',
    subtitle: 'France',
    country: 'France',
    date: '2024',
    cover: '/travel/france/IMG_4028.JPG',
    gallery: [
      { src: '/travel/france/IMG_3779.JPG', alt: '法国' },
      { src: '/travel/france/IMG_3999.PNG', alt: '法国' },
      { src: '/travel/france/IMG_4012.JPG', alt: '法国' },
      { src: '/travel/france/IMG_4022.JPG', alt: '法国' },
      { src: '/travel/france/IMG_4028.JPG', alt: '法国' },
      { src: '/travel/france/IMG_4033.JPG', alt: '法国' },
      { src: '/travel/france/IMG_7473.JPG', alt: '法国' },
    ],
  },
  {
    slug: 'hangzhou',
    name: '杭州',
    subtitle: 'Hangzhou',
    country: 'China',
    date: '2024',
    cover: '/travel/hangzhou/IMG_5951.jpeg',
    gallery: [
      { src: '/travel/hangzhou/FullSizeRender.jpeg', alt: '杭州' },
      { src: '/travel/hangzhou/IMG_5951.jpeg', alt: '杭州' },
      { src: '/travel/hangzhou/IMG_6127.jpeg', alt: '杭州' },
    ],
  },
  {
    slug: 'hongkong',
    name: '香港',
    subtitle: 'Hong Kong',
    country: 'China',
    date: '2025',
    cover: '/travel/hongkong/IMG_4847.JPG',
    gallery: [
      { src: '/travel/hongkong/fxn 2025-05-03 202338.244.jpg', alt: '香港' },
      { src: '/travel/hongkong/fxn 2025-05-03 210232.022.jpg', alt: '香港' },
      { src: '/travel/hongkong/IMG_4847.JPG', alt: '香港' },
      { src: '/travel/hongkong/IMG_4862.jpeg', alt: '香港' },
      { src: '/travel/hongkong/IMG_4864.JPG', alt: '香港' },
      { src: '/travel/hongkong/IMG_5145.JPG', alt: '香港' },
      { src: '/travel/hongkong/IMG_5146.jpeg', alt: '香港' },
      { src: '/travel/hongkong/IMG_5148.JPG', alt: '香港' },
    ],
  },
  {
    slug: 'italy',
    name: '意大利',
    subtitle: 'Italy',
    country: 'Italy',
    date: '2024',
    cover: '/travel/italy/IMG_2593.JPG',
    gallery: [
      { src: '/travel/italy/IMG_2180.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_2593.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_2594.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_2636.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_2724.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_2775.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_2826.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_2855.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_5619.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_5666.JPG', alt: '意大利' },
      { src: '/travel/italy/IMG_6067.JPG', alt: '意大利' },
    ],
  },
  {
    slug: 'japan',
    name: '日本',
    subtitle: 'Japan',
    country: 'Japan',
    date: '2024',
    cover: '/travel/japan/IMG_3275.JPG',
    gallery: [
      { src: '/travel/japan/D8DA5DC8-8466-48FC-B07A-70183F483518-40703-000006A9BE6DA902.jpg', alt: '日本' },
      { src: '/travel/japan/FB88C12A-3291-4566-BEE0-CC9E63A89241-30642-000004DDC8ECA0E3.jpg', alt: '日本' },
      { src: '/travel/japan/IMG_0480.jpeg', alt: '日本' },
      { src: '/travel/japan/IMG_0872.jpeg', alt: '日本' },
      { src: '/travel/japan/IMG_2300.JPG', alt: '日本' },
      { src: '/travel/japan/IMG_2616.JPG', alt: '日本' },
      { src: '/travel/japan/IMG_3266.JPG', alt: '日本' },
      { src: '/travel/japan/IMG_3275.JPG', alt: '日本' },
      { src: '/travel/japan/IMG_3283.JPG', alt: '日本' },
    ],
  },
  {
    slug: 'monaco',
    name: '摩纳哥',
    subtitle: 'Monaco',
    country: 'Monaco',
    date: '2024',
    cover: '/travel/monaco/IMG_3920.JPG',
    gallery: [
      { src: '/travel/monaco/IMG_3907.JPG', alt: '摩纳哥' },
      { src: '/travel/monaco/IMG_3911.JPG', alt: '摩纳哥' },
      { src: '/travel/monaco/IMG_3920.JPG', alt: '摩纳哥' },
      { src: '/travel/monaco/IMG_3927.JPG', alt: '摩纳哥' },
      { src: '/travel/monaco/IMG_7303.JPG', alt: '摩纳哥' },
    ],
  },
  {
    slug: 'shanghai',
    name: '上海',
    subtitle: 'Shanghai',
    country: 'China',
    date: '2024',
    cover: '/travel/shanghai/IMG_0601.JPG',
    gallery: [
      { src: '/travel/shanghai/IMG_0294.JPG', alt: '上海' },
      { src: '/travel/shanghai/IMG_0597.JPG', alt: '上海' },
      { src: '/travel/shanghai/IMG_0601.JPG', alt: '上海' },
      { src: '/travel/shanghai/IMG_4491.JPG', alt: '上海' },
      { src: '/travel/shanghai/IMG_4492.JPG', alt: '上海' },
      { src: '/travel/shanghai/IMG_4500.jpeg', alt: '上海' },
      { src: '/travel/shanghai/IMG_4567.jpeg', alt: '上海' },
      { src: '/travel/shanghai/IMG_7662.JPG', alt: '上海' },
    ],
  },
  {
    slug: 'singapore',
    name: '新加坡',
    subtitle: 'Singapore',
    country: 'Singapore',
    date: '2024',
    cover: '/travel/singapore/IMG_5653.JPG',
    gallery: [
      { src: '/travel/singapore/IMG_5270.JPG', alt: '新加坡' },
      { src: '/travel/singapore/IMG_5276.JPG', alt: '新加坡' },
      { src: '/travel/singapore/IMG_5357.JPG', alt: '新加坡' },
      { src: '/travel/singapore/IMG_5653.JPG', alt: '新加坡' },
      { src: '/travel/singapore/IMG_5689.JPG', alt: '新加坡' },
      { src: '/travel/singapore/IMG_5844.JPG', alt: '新加坡' },
      { src: '/travel/singapore/IMG_5993.JPG', alt: '新加坡' },
      { src: '/travel/singapore/IMG_6030.JPG', alt: '新加坡' },
    ],
  },
  {
    slug: 'suzhou',
    name: '苏州',
    subtitle: 'Suzhou',
    country: 'China',
    date: '2024',
    cover: '/travel/suzhou/IMG_4390.JPG',
    gallery: [
      { src: '/travel/suzhou/IMG_4390.JPG', alt: '苏州' },
      { src: '/travel/suzhou/IMG_4623.jpeg', alt: '苏州' },
      { src: '/travel/suzhou/IMG_4625.jpeg', alt: '苏州' },
      { src: '/travel/suzhou/IMG_4848.jpeg', alt: '苏州' },
    ],
  },
  {
    slug: 'tianjin',
    name: '天津',
    subtitle: 'Tianjin',
    country: 'China',
    date: '2024',
    cover: '/travel/tianjin/IMG_7875.JPG',
    gallery: [
      { src: '/travel/tianjin/IMG_2648.jpeg', alt: '天津' },
      { src: '/travel/tianjin/IMG_6745.jpeg', alt: '天津' },
      { src: '/travel/tianjin/IMG_6759.jpeg', alt: '天津' },
      { src: '/travel/tianjin/IMG_6767.jpeg', alt: '天津' },
      { src: '/travel/tianjin/IMG_7874.JPG', alt: '天津' },
      { src: '/travel/tianjin/IMG_7875.JPG', alt: '天津' },
      { src: '/travel/tianjin/IMG_7891.jpeg', alt: '天津' },
      { src: '/travel/tianjin/IMG_7892.JPG', alt: '天津' },
      { src: '/travel/tianjin/IMG_7955.JPG', alt: '天津' },
      { src: '/travel/tianjin/IMG_7956.JPG', alt: '天津' },
      { src: '/travel/tianjin/IMG_7957.jpeg', alt: '天津' },
      { src: '/travel/tianjin/IMG_7961.jpeg', alt: '天津' },
    ],
  },
  {
    slug: 'wuhan',
    name: '武汉',
    subtitle: 'Wuhan',
    country: 'China',
    date: '2024',
    cover: '/travel/wuhan/IMG_9548.JPG',
    gallery: [
      { src: '/travel/wuhan/IMG_9475.JPG', alt: '武汉' },
      { src: '/travel/wuhan/IMG_9476.JPG', alt: '武汉' },
      { src: '/travel/wuhan/IMG_9487.JPG', alt: '武汉' },
      { src: '/travel/wuhan/IMG_9548.JPG', alt: '武汉' },
      { src: '/travel/wuhan/IMG_9549.JPG', alt: '武汉' },
    ],
  },
  {
    slug: 'xian',
    name: '西安',
    subtitle: "Xi'an",
    country: 'China',
    date: '2024',
    cover: '/travel/xian/IMG_1002.JPG',
    gallery: [
      { src: '/travel/xian/IMG_0967.JPG', alt: '西安' },
      { src: '/travel/xian/IMG_0978.JPG', alt: '西安' },
      { src: '/travel/xian/IMG_1002.JPG', alt: '西安' },
      { src: '/travel/xian/IMG_1022.JPG', alt: '西安' },
      { src: '/travel/xian/IMG_1067.JPG', alt: '西安' },
    ],
  },
  {
    slug: 'zhejiang',
    name: '浙江',
    subtitle: 'Zhejiang',
    country: 'China',
    date: '2023',
    cover: '/travel/zhejiang/IMG_5176.JPG',
    gallery: [
      { src: '/travel/zhejiang/2023-05-02 134957.jpg', alt: '浙江' },
      { src: '/travel/zhejiang/2023-05-02 140059.jpg', alt: '浙江' },
      { src: '/travel/zhejiang/IMG_5176.JPG', alt: '浙江' },
      { src: '/travel/zhejiang/IMG_5177.JPG', alt: '浙江' },
      { src: '/travel/zhejiang/IMG_5589.jpeg', alt: '浙江' },
      { src: '/travel/zhejiang/IMG_5703.jpeg', alt: '浙江' },
      { src: '/travel/zhejiang/IMG_5715.jpeg', alt: '浙江' },
    ],
  },
];

export function getPlaceBySlug(slug: string): TravelPlace | undefined {
  return travelPlaces.find(p => p.slug === slug);
}

export function getAllPlaceSlugs(): string[] {
  return travelPlaces.map(p => p.slug);
}
